#!/bin/bash
declare -r testDir="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )" 
source "$testDir/test.bash"
declare -r TMPDIR="/tmp"

testTrivial() {
  cat >"$tmpDir/1" <<EOF
#!/bin/bash
read line
echo b
sed 'd'
EOF
  chmod +x "$tmpDir/1"
  echo a | reloadable "$tmpDir/1" > "$tmpDir/1.out" &
  local process="$!"
  for ((i=5; i > 0; i--)); do
    if cmp -s <(echo b) "$tmpDir/1.out"; then
      killtree "$process"
      return 0
    else
      sleep 1
    fi
  done
  killtree "$process"
  assertFail
}

testSwitch() {
  echo "test 2"
  cat >"$tmpDir/2" <<EOF
#!/bin/bash
read line;
echo b
while sleep 1; do :; done
EOF
  chmod +x "$tmpDir/2"
  while sleep 1; do echo a; done | reloadable "$tmpDir/2" > "$tmpDir/2.out" &
  local process="$!"
  sleep 1
  cat >"$tmpDir/2" <<EOF
#!/bin/bash
read line;
echo c
sed 'd'
EOF

  for ((i=15; i > 0; i--)); do
    if cmp -s <( echo -e "b\nc") "$tmpDir/2.out"; then
      killtree "$process"
      return 0
    else
      sleep 1
    fi
  done
  killtree "$process"
  assertFail
}

setUpTests
declare tmpDir="$(mktemp -p "$TMPDIR" -d test.XXXXXX)"
runTest testTrivial
runTest testSwitch
rm -r "$tmpDir"
getTestResults
