#!/bin/bash

source "$botDir/lib/utility.sh"

declare -r channel="$2"
declare -r message="${6#*grep }"

declare -a assignableParameters=( m e A B C )
declare -a passThroughFlags=( c i E )

parseArgs $message

if (( "${#vargs[@]}" > 0 )); then
  declare gargs="$( echo "${vargs[*]}")"

  declare -a gflags=( )

  declare re='^[0-9]+$'

  for f in "${passThroughFlags[@]}"; do
    if [[ "${argMap[$f]+_}" ]]; then
      gflags+=( -$f )
    fi
  done

  if [[ "${argMap[C]+_}" && "${argMap[C]}" =~ $re ]]; then
    gflags+=( -C "${argMap[C]}" )
  else 
    if [[ "${argMap[B]+_}" && "${argMap[B]}" =~ $re ]]; then
      gflags+=( -A "${argMap[B]}" )
    fi
    if [[ "${argMap[A]+_}" && "${argMap[A]}" =~ $re ]]; then
      gflags+=( -B "${argMap[A]}" )
    fi
  fi

  if [[ "${argMap[m]+_}" && "${argMap[m]}" =~ $re ]]; then
    gflags+=( -m "${argMap[m]}" )
  fi

  find "$botDir/logs/$channel" -type f -name '*_message' -print0 \
    | sort -rz \
    | xargs -0 tac \
    | grep -vF "$6" \
    | grep "${gflags[@]}" -- "$gargs" \
    | awk -F "\r" '
        /^[0-9]+/{
          if ($5 ~ "message") {
            print "[" strftime("%Y-%m-%d %H:%M:%S",$1) "]", $2 ":", $6
          }
          else if ( $5 ~ "action") {
            print "[" strftime("%Y-%m-%d %H:%M:%S",$1) "]", "*", $2, $6
          }
          else {
            print $0
          }
        }
        /^[^0-9]/{print $0}
      ' \
    | head -n 500 \
    | tac \
    | "$botDir/lib/privorpaste" "$channel" "$(getServerNameLength "$bufferDir")"
fi
