#!/bin/bash

source "$botDir/lib/utility.sh"

declare -r channel="$2"
declare -r message="${6#*man }"

man -M "$botDir/share/man/" "$message" 2>&1 | col -b | privorpaste "$channel" "$(getServerNameLength "$bufferDir")"
