#!/bin/bash

declare -r channel="$2"
declare -r message="${6#*meme }"
declare -r memeFile="$botDir/share/memes"

if [[ ! -e "$memeFile" ]]; then
  exit 2
fi

declare -r filteredMemeString="$(tr A-Z a-z <<< "$message" | sed -E 's/[^a-z0-9 ]//;s/^\s+//')"

if [[ -n "$message" ]]; then
  grep -E -m 1 "(^$filteredMemeString[,:])|(,\s?$filteredMemeString[,:])" "$memeFile" \
    | sed -E 's/[^:]*:\s?(.*)/\1/' \
    | privmsg "$channel"
fi
