#!/bin/bash
declare -r channel="$2"

declare -ri started="$(stat -c %Z "$bufferDir")"
declare -ri current="$(date +%s)"

declare -ri elapsed=$((current - started))

declare -ri seconds=$((elapsed % 60))
declare -ri minutes=$(( (elapsed / 60 ) % 60))
declare -ri hours=$(( (elapsed / 60 / 60) % 24 ))
declare -ri days=$(( elapsed / 60 / 60 / 24 ))

printf "%d days, %d hours, %d minutes, %d seconds\n" $days $hours $minutes $seconds | "$botDir/lib/privmsg" "$channel"
