#!/bin/bash

source "$botDir/lib/utility.sh"
set -f 

declare -r channel="$2"
declare -r message="${6#*wolfram }"

declare result

result="$(curl -G -s "http://api.wolframalpha.com/v2/query" --data-urlencode "input=$message" --data "appid=XXXXXX-XXXXXXXXXX&format=plaintext&podindex=2" \
   | grep -oPz "((?<=title=')[^']+)|((?<=<plaintext>)[^<]+)" \
   | sed '1{N;s/\n/ = /}' \
   | tr '\n' ' ' )"

if [[ -n "$result" ]]; then
  "$botDir/lib/privmsg" "$channel" "$(getServerNameLength "$bufferDir")" <<< "$result"
else
  "$botDir/lib/privmsg" "$channel" "$(getServerNameLength "$bufferDir")" <<< "no results"
fi
