#!/bin/bash

set -f 

declare -r channel="$2"
declare -r message="${6#*wolfram }"

declare -r apiKey="$(cat "$botDir/etc/wolframKey")"

[[ -z $apiKey ]] && exit 2;

declare result

result="$(curl -G -s "http://api.wolframalpha.com/v2/query" --data-urlencode "input=$message" --data "appid=$apiKey&format=plaintext&podindex=2" \
  | grep -oPz "((?<=title=')[^']+)|((?<=<plaintext>)[^<]+)" \
  | sed '1{N;s/\n/ = /}' \
  | tr '\n' ' ' \
  | decodehtml.awk )"

if [[ -n "$result" ]]; then
  privmsg "$channel" "$result"
else
  privmsg "$channel" "no results"
fi
