#!/bin/bash

source $botDir/commandLoader.sh

commandWatcher "$botDir/commands/channel/" "$bufferDir/channel" "$bufferDir/rawOutput.p" &
watcherPid=$!

trap "kill -TERM $watcherPid; exit 1" SIGTERM

awk -v private="$bufferDir/private.p" -v channel="$bufferDir/channel.p" '
BEGIN {
  FPAT=".*"
}

/:?\S+ PRIVMSG #/ {
  print $0 > channel
  fflush(channel)
}

/:?\S+ PRIVMSG [^#]/ {
  print $0 > private
  fflush(private)
}'

