#!/bin/bash

source $botDir/config
password=$(redis-cli get config:password)
trap '' SIGHUP

awk '

/^:?\S+ NOTICE \* :\*\*\* Looking up your hostname\.\.\./{

  print "NICK " nick
  printf("USER %s %s %s :%s\n", user, hostname, servername, realname)
}

/^:?NickServ!NickServ@services\.\s+NOTICE\s+\S+\s+:This nickname is registered./{
  print "NS identify " password
}' user=$USER nick=$NICK realname="$REALNAME" hostname=$HOSTNAME servername=$SERVERNAME password="$password"
