#!/bin/bash

source "$botDir/lib/utility.sh"

set -f

declare -r subRegex='^\S+\s+privmsg\s+#\S+\s+:([^:[:space:]+]*)(\+[1-9][0-9]*)?:s.*$'

substitute() {
  local -ri maxLength="$((510 - $(getheaderlength) - 50))"
  grep --line-buffered -iE "$subRegex" \
    | while read -r line; do
      expression="$(cut -d : -f 3- <<< "$line" | regex.awk)"
      if [ -n "$expression" ]; then

        local -a data=( $(getIRCInfo "$line") ) 
        local targetUser="$(sed -E "s/$subRegex/\\1/i" <<< "$line")"
        local targetLine="$(sed -E "s/$subRegex/\\2/i" <<< "$line")"

        sub "${data[0]}" "$botDir/logs/${data[1]}" "$expression" "$targetUser" "$targetLine" \
          | sed -E 's/^/=> /' \
          | cut -c-"$maxLength" \
          | tr -d "\a\r\v\n" \
          | privmsg "${data[1]}"
      fi
    done
}

startAndWatch substitute
