#!/bin/bash

main() {
  local -r channel="$2"

  {
    printf "Available Commands:\n"
    find "$botLib/simple" -type f -printf "%f\n" \
      | sort \
      | tr "\n" " "
  } | privmsg "$channel"
}

main "$@"
