#!/bin/bash

source "$botLib/utility.sh"

declare -r channel="$2"
declare -r message="$6"

if [[ -z "$message" ]]; then
  privmsg "$channel" "What did you expect that to do?"
else
  if man -w -M "$botShare/man/" "$message" &>/dev/null; then
    geturl "man/$message" | privmsg "$channel"
  else
    printf "No manual entry for %s" "$message" | privmsg "$channel"
  fi
fi
