#!/bin/bash

set -f 

main() {
  source "$botLib/utility.sh"

  local -r nick="$1"
  local -r channel="$2"
  local -r message="$6"

  local -r apiKey="$(< "$botConfig/etc/wolframKey")"

  [[ -z $apiKey ]] && exit 2;

  local result

  result="$(curl -G -s "http://api.wolframalpha.com/v2/query" --data-urlencode "input=$message" --data "appid=$apiKey&format=plaintext&podindex=2" \
    | grep -oaPz "((?<=title=')[^']+)|((?<=<plaintext>)[^<]+)" \
    | sed '1{N;s/\n/ = /}' \
    | tr '\n' ' ' \
    | decodehtml.awk)"

  if [[ -n "$result" ]]; then
    privmsg "$channel" "$result"
  else
    getMessage wolframerror1 "$nick" "$RANDOM" | privmsg "$channel"
  fi
}

main "$@"
