.TH BOTINFO 1
.SH NAME
botinfo \- prints out info about the channel bots
.SH SYNOPSIS
.B botinfo
.SH DESCRIPTION
Prints a string of information about the bots in the current channel. This explains how to get the list of commands and the command help for each bot.

The information is listed in the following format, with one entry for each bot:

.B bot_name
(
.IR list_command, 
.IR help_command_syntax
)

The files for the channels are stored in share/botInfo/channel_name.
