.TH MAN 1
.SH NAME
man \- look up help for command
.SH SYNOPSYS
.B man
.IR command
.SH DESCRIPTION
.B man
generates the man page for the specified command then posts a link in the channel where you can access it. 
.PP
If you want to list the available commands you should use the
.B ls
command instead.
