.TH UNSHORT 1
.SH NAME
unshort \- get the full version of a shortened url
.SH SYNOPSIS
.B unshort
[url]
.SH DESCRIPTION
Queries unshorten.it to get the full url for a shortened url.

If no url is provided it will grab the last url used in the current channel(note it only checks today's logs).

It requires that you put your unshorten.it api key in ~/.shellby/etc/unshortenKey.
