.TH UPTIME 1
.SH NAME
uptime \- prints how long shellby has been up for
.SH SYNOPSIS
.B uptime
.SH DESCRIPTION
This command will print how long shellby has been up for. If the current uptime is not the best recorded uptime, the best recorded uptime will also be printed.

No it is not late, shellby is supposed to be up at this time.
