.TH URBAN 1
.SH NAME
urban \- get Urban Dictionary definitions
.SH SYNOPSIS
.B urban
[ -n index ] [ -e ]
search_string
.SH DESCRIPTION
Queries Urban Dictionary with the search string you give it.
.SH OPTIONS
.IP "-n index"
Specifies the index of the definition to print.
.IP -e
Grab the example instead of the definition.
