.TH URBAN 1
.SH NAME
urban \- get Urban Dictionary definitions
.SH SYNOPSIS
.B urban
.RB [ -n
.IR index ]
.RB [ -e ]
.I search_string
.SH DESCRIPTION
Queries Urban Dictionary with the search string you give it.
.SH OPTIONS
.TP 
.B -n \fIindex\fP
Specifies the index of the definition to print.
.TP 
.B -e
Grab the example instead of the definition.
