.TH YOUTUBE 1
.SH NAME
youtube \- get the title for a youtube video
.SH SYNOPSIS
.B youtube
[url]
.SH DESCRIPTION
Grabs the title of a video from the youtube api.

If no url is provided it will grab the last url used in the current channel(note it only checks today's logs).

It requires that you put your youtube v3 api key in ~/.shellby/etc/youtubeKey.
