#!/bin/bash

declare nickname="$(< "$bufferDir/etc/nickname")"

declare username
declare hostname

if [[ -f "$bufferDir/etc/username" && -f "$bufferDir/etc/hostname" ]]; then
  username="$(< "$bufferDir/etc/username")"
  hostname="$(< "$bufferDir/etc/hostname")"
else
  username="$USER"
  hostname="$HOSTNAME"
fi

printf ":%s!%s@%s  " "$nickname" "$username" "$hostname" | wc -c
