#!/bin/bash

main() {
  if ! type readProperties &>/dev/null; then
    source "$botLib/readprop.sh"
  fi

  readProperties "$botConfig/etc/config"

  local -r port="${properties[serverPort]-40156}"
  local domain
  if [[ -z "${properties[serverDomain]}" ]]; then
    domain="$(< "$bufferDir/etc/hostname")"
  else
    domain="${properties[serverDomain]}"
  fi

  if [[ "${properties[port80]}" == "true" ]]; then
    printf "http://%s/%s\n" "$domain" "$1"
  else
    printf "http://%s:%d/%s\n" "$domain" "$port" "$1"
  fi
  
}

main "$@"
