#!/bin/bash

###############
# load config #
###############

declare -r botDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )" 
export botDir

PATH="$botLib:$PATH"
export PATH

export botConfig
export botLib
export botShare

declare -r botLogs="$botConfig/logs"
export botLogs

source "$botConfig/etc/config"

declare -r bufferDir="$(mktemp -p "$TMPDIR" -d streambot.XXXXXX)"
export bufferDir

source "$botLib/loadConfig.sh"

################
# toggle debug #
################

[ ! -z "$DEBUG" ] && set -x

#########################
# set up signal handler #
#########################

trap "rm -rf $bufferDir; exit 1" SIGINT SIGTERM EXIT

#####################
# load dependencies #
#####################

source "$botLib/commandLoader.sh"

###################
# Test Connection #
###################

while ! netcat -z -w 5 $TARGETSERVER $PORT; do
  sleep 1
done

#################
# start the bot #
#################

date +%s > "$bufferDir/etc/lastContact"

mkfifo "$bufferDir/toNetcat" "$bufferDir/fromNetcat"
managePipes "$botLib/commands/" "$bufferDir/toNetcat" "$bufferDir/fromNetcat"

stdbuf -oL netcat -i 1 $TARGETSERVER $PORT < "$bufferDir/toNetcat" \
  | sed -u 's/$//' \
  | tee "$bufferDir/fromNetcat" \
  | grep --line-buffered "^"  & 
declare -ri pipelinePid=$!

echo started

trap reloadAllConfig SIGHUP

watchFiles "$botLib/commands/" "$bufferDir/toNetcat" "$bufferDir/fromNetcat"

wait $pipelinePid 

kill -USR1 $thisPid
