#!/bin/bash

###############
# load config #
###############

export botPid="$$"

declare -r botDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )" 
export botDir

PATH="$botLib:$PATH"
export PATH

export botConfig
export botLib
export botShare

declare -r botLogs="$botConfig/logs"
export botLogs

source "$botConfig/etc/config"

declare -r bufferDir="$(mktemp -p "$TMPDIR" -d streambot.XXXXXX)"
export bufferDir

source "$botLib/loadConfig.sh"

################
# toggle debug #
################

[ ! -z "$DEBUG" ] && set -x

#########################
# set up signal handler #
#########################

trap "rm -rf $bufferDir; exit 1" SIGINT SIGTERM EXIT

#####################
# load dependencies #
#####################

source "$botLib/commandLoader.sh"

###################
# Test Connection #
###################

while ! netcat -z -w 5 $TARGETSERVER $PORT; do
  sleep 1
done

#################
# update uptime #
#################

date +%s > "$bufferDir/etc/lastContact"

if [[ -f "$botLogs/uptimeStats" ]]; then
  declare uptimeStats="$(gawk '
    {
      current = strftime("%s")
      previousValue = $1
      first = $2
      last = $3
      newValue = (previousValue * (last - first)) / (current - first)
      printf("%.12g %d %d", newValue, first, current)
    }

    ' < "$botLogs/uptimeStats")"
  echo "$uptimeStats" > "$botLogs/uptimeStats"
fi

#################
# start the bot #
#################

mkfifo "$bufferDir/toNetcat" "$bufferDir/fromNetcat"
managePipes "$botLib/commands/" "$bufferDir/toNetcat" "$bufferDir/fromNetcat"

stdbuf -oL netcat -i 1 $TARGETSERVER $PORT < "$bufferDir/toNetcat" \
  | sed -u 's/$//' \
  | tee "$bufferDir/fromNetcat" \
  | grep --line-buffered "^"  & 
declare -i pipelinePid=$!

echo started

trap reloadAllConfig SIGHUP

{
  while ! ps -p $pipelinePid >/dev/null 2>&1; do
    sleep 5
  done 

  while ps -p $pipelinePid >/dev/null 2>&1; do
    sleep 5
  done 

  echo "!!! Netcat died. Reloading Main."

  kill -USR1 $thisPid
} &

watchFiles "$botLib/commands/" "$bufferDir/toNetcat" "$bufferDir/fromNetcat"

