#!/bin/bash

set -f

declare -r channel="$1"
declare -r message="$2"

if [[ -z "$channel" ]]; then
  exit 1;
fi

if [[ -n "$message" ]]; then
  printf "NOTICE\r\r%s\r%s\n" "$channel" "$message"
else
  printf "NOTICE\r\r%s\r%s\n" "$channel" "$(cat)"
fi
