#!/bin/bash

source "$botLib/utility.sh"

main() {
  local -r channel="$1"

  local -r cacheDir="$bufferDir/cache/pastebin"
  local -r pasteDir="$bufferDir/web/paste"

  if [[ ! -d "$cacheDir" ]]; then
    mkdir -p "$cacheDir"
  fi

  if [[ ! -d "$pasteDir" ]]; then
    mkdir -p "$pasteDir"
  fi

  trimCache "$pasteDir" "$((5 * 1024 * 1024))"

  local -r tmpFile="$(mktemp -p "$cacheDir" tmp.XXXXXX)"
        
  cat - \
    | sed -E '
      # escaping
      s/&/\&amp;/g
      s/>/\&gt;/g
      s/</\&lt;/g
      s/"/\&quot;/g
      s/'"'"'/\&#39;/g
      s% {2,}%<pre>&</pre>%g

      #s (http://)?'"$HOSTPORT$ABS_PATH#?($PCHAR|[/?])*"' <a\ href="&">&</a> g
      s/$/<br>/
      ' > "$tmpFile"

  local -r checksum="$(md5sum "$tmpFile" | head -c 10)"

  mv "$tmpFile" "$pasteDir/$checksum"

  geturl "paste/$checksum" | privmsg "$channel"
}

main "$@"
