#!/bin/bash

declare badRequest="^Bad API request,"
declare -r apiKey="$1"

declare reply="$(curl --data "api_option=paste&api_dev_key=$apiKey&api_paste_private=1&api_paste_expire_date=1D" --data-urlencode "api_paste_code=$(cat)" 'http://pastebin.com/api/api_post.php')"

if (( $? != 0 )); then
  echo Request failed >&2
  exit 1
fi

if [[ $reply =~ $badRequest ]]; then
  echo "$reply" >&2
  exit 1
fi

echo "$reply"
