#!/bin/bash

set -f

declare -r channel="$1"
declare -r message="$2"
declare -ri headerLength="$(getheaderlength)"

if [[ -z "$channel" ]]; then
  exit 1;
fi

declare -r shellbyHostname="$(< "$bufferDir/etc/nickname")!$(< "$bufferDir/etc/username")@$(< "$bufferDir/etc/hostname")"

if [[ -n "$message" ]]; then
  printf "%s\n" "$message"
else
  cat
fi \
  | wrap "PRIVMSG $channel :" "$headerLength" \
  | tee >( logCommand "$shellbyHostname" )

exit $?

