#!/bin/bash

# Take the contents of stdin and get a pastebin link for them
#
# This caches paste links for 6 days.
# Expired old pastes are not cleaned up automatically.
pastebin() {
  if [[ ! -d "$cacheDir" ]]; then
    mkdir -p "$cacheDir"
  fi

  local -r tmpFile="$(mktemp -p "$cacheDir" tmp.XXXXXX)"
  cat - > "$tmpFile"

  local -r checksum="$(md5sum "$tmpFile" | cut -f1 -d" ")"
  local -r cachedFile="$cacheDir/md5.$checksum"

  if [[ -f "$cachedFile" ]]; then
    cat $cachedFile
  else
    curl -si -F "content=<$tmpFile" "http://dpaste.com/api/v2/" \
      | sed -E -n '
        s/^Location: //
        T
        s/\s+$/#wrap/
        p' \
      | tee "$cachedFile"
  fi
  
  rm "$tmpFile"
}

main() {
  local -r channel="$1"

  local -r cacheDir="$bufferDir/cache/pastebin"

  read -r line1
  read -r line2

  if (( $? != 0 )); then
    privmsg "$channel" "$line1"
  else
    cat <( echo "$line1" ) <(echo "$line2") - \
      | pastebin \
      | privmsg "$channel"
  fi
}

main "$@"
