#!/bin/bash

# Pastebins the input if it is more than one line
#
# Warning: the line that this outputs can still be broken by wrap
#
# 1.channel the channel or user to send the output to
# &0. the message to privmsg or paste
main() {
  local -r channel="$1"

  read -r line1
  read -r line2

  if (($? != 0)); then
    privmsg "$channel" "$line1"
  else
    cat <(printf "%s\n" "$line1") <(printf "%s\n" "$line2") - | pastebin "$channel"
  fi
}

main "$@"
