#!/bin/bash

set -f

main() {
  local -r user="$1"
  local -r logDir="$2"

  local -r expression="$3"
  local -r targetUser="${4:-$user}"
  local -r targetLine="${5:-0}"

  local -r cacheDir="$bufferDir/cache/errors"

  if [[ ! -d "$cacheDir" ]]; then
    mkdir -p "$cacheDir"
  fi

  local -r tmpFile="$(mktemp -p "$cacheDir" tmp.XXXXXX)"

  find $logDir -name "*_message" -type f -print0 \
    | sort -rz \
    | sed -n -z "1,2p" \
    | xargs -0 tac \
    | gawk -F "\r" '
      BEGIN {
        count = 0
      }

      $2 == nick {
        if ( ! ($6 ~ /^[^:[:space:]+]*(\+[1-9][0-9]*)?:s/)) {
          if (count == targetLine) {
            print $6
            exit 0
          } else {
            count += 1
          }
        }
      }' nick="$targetUser" targetLine="$targetLine" \
    | sed -E "$expression" 2>"$tmpFile"

  if (( $? != 0 )); then
    local -r sedError="$(head -n 1 "$tmpFile")"
    if [[ -n "$sedError" ]]; then
      sed 's/sed: -e expression #1,/Error at/' <<< "$sedError"
    fi
  fi

  rm "$tmpFile"
}

main "$@"
