#!/bin/bash

declare -r user="$1"
declare -r logDir="$2"

declare -r search="$3"
declare -r replace="$4"
declare match="$5"

declare -a logFiles=($(find $logDir -type f | sort -r | head -n 2))

tac "${logFiles[@]}" |awk '$2 == userString  {
  if($0 ~ /^\S+\s+\S+\s+:/ && ! ($0 ~ /^\S+\s+\S+\s+: ?:s\/([^\/]|(\\(\\\\)*\/))+\/([^\/]|(\\(\\\\)*\/))*\/g?$/))
  {
    s=$0
    sub(/^\S+\s+\S+\s+: ?/,"",s)
    s=gensub(searchString, replaceString, matchCount, s)
    print s
    exit 0
  }
}
' searchString="$search" replaceString="$replace" userString="$user" matchCount="$match"
