#!/bin/bash
set -f

source "$botLib/readprop.sh"

main() {
  readProperties "$botConfig/etc/config"

  local -r port="${properties[serverPort]-40156}"

  local -r webDir="$bufferDir/web"
  mkdir -p "$webDir" &>/dev/null
  # TODO push ncat down into an executable to make self contained
  env -i thisPid=$thisPid DEBUG="${properties[debug]}" botConfig="$botConfig" botLib="$botLib" botShare="$botShare" bufferDir="$bufferDir" PATH="$PATH" ncat -lk -p "$port" -e "$botLib/web/server"
  
}

main
