#!/bin/bash

source "$botLib/irc.sh"

declare -r COMMAND_REGEX="^PRIVMSG"

main() {
  # TODO add restarting for when these files are actually updated
  local nickname
  local username
  local hostname
  local -i prefixLength

  local withoutSuffix
  local -i metaLength
  local -i length
  local line
  while read -r line; do
    if [[ "$line" =~ $COMMAND_REGEX ]]; then
      nickname="$(< "$bufferDir/etc/nickname")"
      username="$(< "$bufferDir/etc/username")"
      hostname="$(< "$bufferDir/etc/hostname")"
      prefixLength="$(printf ":%s!%s@%s " "$nickname" "$username" "$hostname" | wc -c)"

      withoutSuffix="$(sed -E 's/[^\r]*$//' <<<"$line")"
      ((length = 510 - prefixLength - ${#withoutSuffix}))
      sed -E 's/^.*\r//' <<<"$line" | fold -s -w "$length" | xargs -d "\n" printf "$withoutSuffix%s\n"
    else
      printf "%s\n" "$line"
    fi
  done
}

main
