#!/bin/bash

declare -r meta="$1"
declare -ri headerLength="$2"
declare -i length

if [[ -z "$meta" ]]; then
  exit 1;
fi

length="$((510 - $headerLength - $(wc -c <<< "$meta")))"

fold -s -w $length | xargs -d "\n" printf "$meta%s\n"
