#!/bin/bash

source "$botLib/http.sh"
source "$botLib/blate.sh"
source "$botLib/utility.sh"

source "$botLib/web/man.bash"
source "$botLib/web/paste.bash"
source "$botLib/web/log.bash"

serveRootFiles() {
  local -r file="${3#/}"
  serveFile "$botShare" "$file"
  return $?
}

serveBadFile() {
  sendResponsePipe 200 <"$botShare/badfile"
  return 0
}

main() {
  addRoute GET '^/(robots.txt|favicon.ico)$' serveRootFiles
  addRoute GET '^/man/' serveMan
  addRoute GET '^/paste/' servePastes
  addRoute GET '^/badfile$' serveBadFile
  addRoute GET '^/log/paste/' serveLogPaste

  runServer
}

main "$@"
