#!/bin/bash

source "$botLib/http.sh"
 
declare -r TMP_MAN_FOLDER="$bufferDir/web/man"
declare -ri MAX_CACHE_SIZE="$((10*1024*1024))"
declare -r MAN_REGEX='^[a-zA-Z0-9_-]+$'
declare -r MAN_SECTION_REGEX='^[0-9]/[a-zA-Z0-9_-]+$'

trimCache() {
  local -r folder="$1"
  local -ri max_size="$2"

  find "$folder" -type f -printf "%T@/%s/%f\0" \
    | sort -nr -z \
    | gawk '
      BEGIN {
        FS="/"
        RS="\0"
        size=0
        MAX_SIZE=strtonum(MAX_SIZE)
      }

      {
        size+=strtonum($2)
        if (size > MAX_SIZE) {
          printf("%s/%s\0", folder, $3)
        }
      }
      ' MAX_SIZE="$max_size" folder="$folder" \
    | xargs -0 -r rm
}

serveMan() {
  local file="${3#/man/}"

  local section
    
  if [[ "$file" =~ $MAN_SECTION_REGEX ]]; then
    section="${file:0:1}"
    file="${file:2}"
  elif [[ ! "$file" =~ $MAN_REGEX ]]; then
    return 1
  fi

  mkdir -p "$TMP_MAN_FOLDER" &>/dev/null

  local manFile="$(man -M "$botShare/man/" -w "$file")"
  local hashName="$(md5sum <<< "$manFile" | head -c 10)"
  local cacheFile="$TMP_MAN_FOLDER/$hashName"

  local -i cachedTime=0
  if [[ -f "$cacheFile" ]]; then
    cacheTime="$(stat -c %Y "$cacheFile")"
  fi
  local -i changeTime="$(stat -c %Y "$manFile")"

  if ((cachedTime == 0 || cachedTime > changeTime )); then
    trimCache "$TMP_MAN_FOLDER" "$MAX_CACHE_SIZE"

    local command
    printf -v command "%q %q" "$botLib/convertPipe" "$cacheFile"

    if [[ -n "$section" ]]; then
      MANWIDTH=80 man -M "$botShare/man/" -P "$command" "$section" "$file" > /dev/tty
    else
      MANWIDTH=80 man -M "$botShare/man/" -P "$command" "$file" > /dev/tty
    fi
  fi

  serveFile "$TMP_MAN_FOLDER" "$hashName"
  return $?
}

main() {
  addRoute GET '^/man/' serveMan

  runServer
}

main "$@"
