#!/bin/bash

source "$botLib/http.sh"
source "$botLib/blate.sh"
source "$botLib/utility.sh"
 
declare -r TMP_MAN_FOLDER="$bufferDir/web/man"
declare -ri MAX_CACHE_SIZE="$((10*1024*1024))"
declare -r MAN_REGEX='^[a-zA-Z0-9_-]+$'
declare -r MAN_SECTION_REGEX='^[0-9]/[a-zA-Z0-9_-]+$'


serveMan() {
  local file="${3#/man/}"

  local section
    
  if [[ "$file" =~ $MAN_SECTION_REGEX ]]; then
    section="${file:0:1}"
    file="${file:2}"
  elif [[ ! "$file" =~ $MAN_REGEX ]]; then
    return 1
  fi

  mkdir -p "$TMP_MAN_FOLDER" &>/dev/null

  local manFile="$(man -M "$botShare/man/" -w "$file")"
  local hashName="$(md5sum <<< "$manFile" | head -c 10)"
  local cacheFile="$TMP_MAN_FOLDER/$hashName"

  local -i cachedTime=0
  if [[ -f "$cacheFile" ]]; then
    cacheTime="$(stat -c %Y "$cacheFile")"
  fi
  local -i changeTime="$(stat -c %Y "$manFile")"

  if ((cachedTime == 0 || cachedTime > changeTime )); then
    trimCache "$TMP_MAN_FOLDER" "$MAX_CACHE_SIZE"

    local command
    printf -v command "%q %q" "$botLib/convertPipe" "$cacheFile"

    if [[ -n "$section" ]]; then
      MANWIDTH=80 man -M "$botShare/man/" -P "$command" "$section" "$file" > /dev/tty
    else
      MANWIDTH=80 man -M "$botShare/man/" -P "$command" "$file" > /dev/tty
    fi
  fi

  serveFile "$TMP_MAN_FOLDER" "$hashName"
  return $?
}

declare -r PASTE_DIR="$bufferDir/web/paste"
declare -r HEX='^[a-f0-9]+$'

servePastes() {
  local file="${3#/paste/}"

  if [[ "$file" =~ $HEX ]]; then
    local -r target="$(find "$PASTE_DIR" -type f -print0 | grep -Fzx -m 1 "$PASTE_DIR/$file")"
    if [[ -n "$target" && -f "$target" ]]; then
      render "$botLib/web/paste.html" | sendResponseChunked 200
      return 0
    fi
  fi
  return 1
  
}

serveRootFiles() {
  local -r file="${3#/}"
  serveFile "$botShare" "$file"
  return $?
}

main() {
  addRoute GET '^/(robots.txt|favicon.ico)$' serveRootFiles
  addRoute GET '^/man/' serveMan
  addRoute GET '^/paste/' servePastes

  runServer
}

main "$@"
