#!/bin/bash

declare -a parts

grep -E --line-buffered "^[0-9]{3}" <&0 | while IFS=$'\r' read -r -a parts; do
  case "${parts[0]}" in
    001)
      # TODO the events folder needs to be deprecated
      "$botLib/events/connected"
      ;;
    311)
      "$botLib/events/whois" "${parts[@]:3:3}"
      ;;
  esac
done
