#!/bin/bash

set -f

source "$botLib/irc.sh"
source "$botLib/users.sh"

main() {
  local botName="$(< "$bufferDir/etc/nickname")" 
  local -a data
  local nick
  local username
  local hostname
  local -a fields

  grep --line-buffered -iE "^invite" \
    | while read -r line; do
      data=( $(getIRCInfo "$line") ) 
      nick="${data[0]}"
      username="${data[3]}"
      hostname="${data[4]}"
      if verify "$nick" "$username" "$hostname"; then
        fields=( $(getFields "$line" 2 3) )
        if [[ "${fields[0]}" == "$botName" ]]; then
          senddelim JOIN "${fields[1]}"
        fi
      fi
    done
}

main
