#!/bin/bash

set -f

source "$botLib/irc.sh"

parseCommands() {

  local botName="$(< "$bufferDir/etc/nickname")" 
  if [[ -z "$botName" ]]; then
    source "$botLib/readprop.sh"
    readProperties "$botConfig/etc/config"
    botName="${properties[nick]}"
  fi

  local -a data
  local message
  local command
  local commandName
  local justMessage

  grep --line-buffered -iE "^privmsg[^]+((#[^]+(($botName\>)|(\./)))|([^#]+))" \
    | while read -r line; do
      data=( $(getIRCInfo "$line") ) 
      message="$(getMessageNoNick "$line" "$botName")"

      command="${message%%[[:space:]]*}"
      commandName="${command##./}"
      if [[ ! $commandName =~ [^a-zA-Z0-9] ]]; then
        justMessage="$(sed -E 's/^\s+//' <<< "${message##$command}")"
        if [[ -e "$botLib/simple/$commandName" ]]; then
          # run command with the following params
          # FROMNICK FROMNICK/CHANNEL CMD USERNAME HOSTNAME COMMAND_PARAMS RAW_MESSAGE
          "$botLib/simple/$commandName" "${data[@]}" "$justMessage" "$message" &
        fi
      fi
    done
}

parseCommands
