#!/bin/bash

declare -r channel="$2"
declare -r message="${6#*gh }"

declare -r hugFile="$botShare/hugs.irc.final"


[[ ! -e "$hugFile" ]] && exit 2

shuf -n 1 "$hugFile"  | sed -E 's/^[0-9]+	//' | tr "" "\n" | privmsg "$channel"
