#!/bin/bash

# given the current line in the markov file get the next
#
# 1.line the current line
# 2.markovFile the file with markov data
getMarkovLine() {
  local -r line="$1"
  local -r markovFile="$2"
  
  local -i lineNumber="$(gawk '
    BEGIN {
      srand(systime() + PROCINFO["pid"] * 31) 
    }

    {
      split($1, first, ":");
      total = first[2];
      selected = rand() * total;
      #print selected > "/dev/stderr"
      soFar = 0;
      for (i=2; i <= NF; i++) {
        #print $i > "/dev/stderr"
        split($i, parts, ":");
        soFar = soFar + parts[2];
        if (selected < soFar) {
          print parts[1];
          exit 0;
        }
      }
    }' <<< "$line")"

  sed -n "$lineNumber{p;q}" "$markovFile"
}

# get a full markov grouphug
getMarkov() {
  local -r markovFile="$botShare/hugs.markov"
  local line
  if (( $# > 0 )); then
    echo "$@" >&2
    local startToken="$( sed "s/[^a-zA-Z0-9'-]//g" <<< "$1" )"
    if [[ -z "$startToken" ]]; then
      echo "I can't work with that."
      return 1
    fi
    line="$(grep -m 1 -i "^$startToken:" "$markovFile")"
    if [[ -z "$line" ]]; then
      echo "There is no $startToken in the database."
      return 1
    fi
  else
    line="$(head -n 1 "$markovFile" )"
  fi

  while grep -qE "^[{}]" <<< "$line"; do
    line="$( getMarkovLine "$line" "$markovFile" )"
  done
    
  while ! grep -qE "^}" <<< "$line"; do
    printf "%s " "${line%%:*}"
    line="$( getMarkovLine "$line" "$markovFile" )"
  done \
    | sed -E '
      s/ $/./
      s/.*/\u&/'
}

main() {
  set -f

  local -r channel="$2"
  local -r message="$6"

  source "$botLib/utility.sh"

  resplitAndParse "$message"

  if [[ "${argMap[m]+_}" ]]; then
    getMarkov "${vargs[@]}" | privmsg "$channel"
  else
    local -r hugFile="$botShare/hugs.irc.final"

    [[ ! -e "$hugFile" ]] && exit 2

    if (( ${#vargs[@]} > 0 )); then
      local -a gflags=( -i -E -m 100 )
      grep "${gflags[@]}" -- "${vargs[*]}" "$hugFile" \
        | sed -E '
          s/^[0-9]+	//
          s/$/\n----------/
          s//\n/g' \
        | sed '$d' \
        | ifEmpty "No one has ever felt the need to confess something like that." \
        | privorpaste "$channel"
    else
      shuf -n 1 "$hugFile" \
        | sed -E 's/^[0-9]+	//' \
        | tr "" "\n" \
        | privmsg "$channel"
    fi
  fi
}

main "$@"
