#!/bin/bash

set -f

reloadModules() {
  if (( $# > 1 )); then
    shift
    printf "%s\n" "$@" >> "$bufferDir/modules/reload"
  fi
}

# send the list of running modules to the target
#
# 1.target the person to send the modules to
printModules() {
  local -r target="$1"

  cat "$bufferDir/modules/list" | tr "\n" " " | privmsg "$target" 
}

main() {
  local -r nickname="$1"
  local -r channel="$2"
  local -r username="$4"
  local -r hostname="$5"
  local -r message="$6"

  source "$botLib/utility.sh"
  source "$botLib/users.sh"

  if ! verify "$nickname" "$username" "$hostname"; then
    notice "$nickname" "What do you think you are trying to do?"
    exit 0
  fi

  resplitAndParse "$message" 

  if (( "${#vargs[@]}" > 0 )); then
    case "${vargs[0]}" in
      reload)
        reloadModules "${vargs[@]}"
        ;;
      list)
        printModules "$channel"
        ;;
    esac
  fi
}

main "$@"
