#!/bin/bash

set -f

declare -A INTERPRETER
INTERPRETER["py"]="import sys;from code import InteractiveInterpreter;InteractiveInterpreter().runsource(sys.stdin.read())"
INTERPRETER["py3"]="import sys;from code import InteractiveInterpreter;InteractiveInterpreter().runsource(sys.stdin.read())"
INTERPRETER["rb"]="print(eval(STDIN.read))"

declare -A LANGUAGE
LANGUAGE["py"]="python/cpython-2.7.8"
LANGUAGE["py3"]="python/cpython-3.4.1"
LANGUAGE["rb"]="ruby/mri-2.3"

getOutput() {
  sed -E 's/"[:,]"/\n/g;s/^[[{]"/\n/g;s/"[]}$]/\n/g' | sed -n '9p' | jsondecode | tee /dev/stderr
}

sendCode() {
  local -r executable="$1"
  local -r language="${LANGUAGE[$executable]}"
  local -r interpreter="${INTERPRETER[$executable]}"

  curl -is "https://eval.in/" -F "code=$interpreter" -F "input=<-" -F "lang=$language" -F "utf8=%CE%BB" -F "execute=on" \
    | tee /dev/stderr \
    | sed -En '
      s/^Location: //

      # if location line print and quit
      T
      p;q'\
    | tr -d "\n\r"
}

main() {
  local -r channel="$2"
  local -r message="$6"
  local -ri headerLength="$(getheaderlength)"
  local -A languages=()

  local -r filename="$(basename "$0")"

  source "$botLib/utility.sh"
  source "$botLib/parseArgs.sh"

  IFS=" "
  local -a splitMessage=( $message )
  unset IFS
  parseArgs "${splitMessage[@]}"

  local url="$(sendCode "$filename" <<< "${vargs[@]}")"
  if [[ -n "$url" ]]; then 
    local json="$(curl -s "$url.json" | getOutput)"
    local reply="$json (${url})"

    local length="$(wc -c <<< "$reply")"
    local lines="$(wc -l <<< "$reply")"

    if ((length + headerLength < 508 && lines <= 1)); then
      printf "=> %s\n" "$reply"| privmsg "$channel" 
    else
      printf "%s\n" "$url" | privmsg "$channel"
    fi
  fi
}

main "$@"
