#!/bin/bash

set -f

main() {
  local -r nickname="$1"
  local -r channel="$2"
  local -r username="$4"
  local -r hostname="$5"
  local -r message="${6#*restart }"

  source "$botLib/users.sh"
  source "$botLib/utility.sh"

  resplitAndParse "$message"

  if verify "$nickname" "$username" "$hostname"; then
    if [[ "${argMap[f]+_}" ]]; then
      kill -USR2 $thisPid
    else
      kill -USR1 $thisPid
    fi
  else
    notice "$nickname" "I don't really like being bossed around. Try ./please"
  fi
}

main "$@"
