#!/bin/bash

set -f

declare -r nickname="$1"
declare -r channel="$2"
declare -r username="$4"
declare -r hostname="$5"
declare -r message="${6#*restart }"

source "$botLib/users.sh"
source "$botLib/utility.sh"

resplitAndParse "$message"

if verify "$nickname" "$username" "$hostname"; then
  if [[ "${argMap[f]+_}" ]]; then
    kill -USR2 $thisPid
  else
    kill -USR1 $thisPid
  fi
else
  notice "$nickname" "I don't really like being bossed around. Try ./please"
fi
