#!/bin/bash
#
# Command which uses unshorten.it to get full urls from shortened ones

set -f 

source "$botLib/utility.sh"

# Search today's logs for the most recent url
#
# stdout: the text of the last shared link
#
# 1.searchChannel the channel to search in
getLastUrl() {
  local -r searchChannel="$1"
  local -r date="$(date +%Y/%m/%d)"

  local -r logFile="$botConfig/logs/$searchChannel/${date}_message"

  tac "$logFile" | awk -F "\r" '{print $6}' | grep -i -o -m 1 -P "$urlRegex"
}

main() {
  #############
  # Arguments #
  #############

  local -r channel="$2"
  local -r message="${6#*unshort}"

  ########
  # Main #
  ########

  local -r apiKey="$(cat "$botConfig/etc/unshortenKey")"

  [[ -z $apiKey ]] && exit 2;

  local searchUrl

  if [[ -z "$message" ]]; then
    searchUrl="$(getLastUrl "$channel")"
  else
    searchUrl="$message"
  fi

  if [[ -z "$searchUrl" ]]; then
    privmsg "$channel" "You want me to look up what now?"
    exit 0
  fi

  local url

  url="$( curl -G -s -m 10 http://api.unshorten.it/ --data "apiKey=$apiKey" --data-urlencode "shortURL=$searchUrl")"
  if (( $? == 0 )); then
    if [[ "$url" =~ ^error ]]; then
      privmsg "$channel" "Their server is very rude. I was saying \"Hello, could you unshorten $searchUrl please?\" and it just said \"ERROR (0)\"."
    else
      privmsg "$channel" "$searchUrl = $url"
    fi
  else
    privmsg "$channel" "That didn't work."
  fi
}

main "$@"
