#!/bin/bash

set -f 

main() {

  local -r nick="$1"
  local -r channel="$2"
  local -r message="${6#*wolfram }"

  local -r apiKey="$(cat "$botConfig/etc/wolframKey")"

  [[ -z $apiKey ]] && exit 2;

  local -ra errorMessages=(
    "Wolfram could not make heads or tails of your query. For more info give them a call at 1-800-WOLFRAM and mention this error code: $RANDOM."
    "So wolfram doesn't seem to be able to solve that one. Wait while I check mycourses to see if anyone else has figured it out."
    "Sorry $nick the query came back empty."
  )

  local result

  result="$(curl -G -s "http://api.wolframalpha.com/v2/query" --data-urlencode "input=$message" --data "appid=$apiKey&format=plaintext&podindex=2" \
    | grep -oaPz "((?<=title=')[^']+)|((?<=<plaintext>)[^<]+)" \
    | sed '1{N;s/\n/ = /}' \
    | tr '\n' ' ' \
    | decodehtml.awk )"

  if [[ -n "$result" ]]; then
    privmsg "$channel" "$result"
  else
    local -ri selectedMessage="$(( $RANDOM % ${#errorMessages[@]} ))"
    privmsg "$channel" "${errorMessages[$selectedMessage]}"
  fi
}

main "$@"
