#!/bin/bash

source "$botLib/readprop.sh"
readProperties "$botConfig/etc/config"

if [[ "${properties[channels]}" ]]; then 
  xargs -n 1 printf "JOIN\r\r%s\n" <<< "${properties[channels]}"
fi

printf "WHOIS\r\r%s\n" $(< "$bufferDir/etc/nickname") &
