#!/bin/bash

source "$botLib/readprop.sh"
readProperties "$botConfig/etc/config"

if [[ "${properties[channels]}" ]]; then 
  xargs -n 1 printf "JOIN %s\n" <<< "${properties[channels]}"
fi

printf "WHOIS %s\n" $(< "$bufferDir/etc/nickname") &
