#!/bin/bash

source "$botLib/readprop.sh"
readProperties "$botConfig/etc/config"

if [[ "${properties[channels]}" ]]; then 
  xargs -n 1 echo "JOIN" <<< "${properties[channels]}"
fi

echo WHOIS $(< "$bufferDir/etc/nickname") &
