#!/bin/bash

declare -r nick="$1"
declare -r username="$2"
declare -r host="$3"

declare -r currentNick="$(< "$bufferDir/etc/nickname")"

if [[ "$nick" == "$currentNick" ]]; then
  printf "%s\n" "$username" > "$bufferDir/etc/username"
  printf "%s\n" "$host" > "$bufferDir/etc/hostname"
fi

