#!/bin/bash

source $botDir/config

while true; do
  if grep -qE '^connect' - ; then
    sleep 0.5
    if [ ! -z "$CHANNELS" ] && [ "${#CHANNELS[@]}" -gt 0 ]; then 
      for channel in "${CHANNELS[@]}"; do
        echo JOIN "$channel"
      done
    fi
  fi
done
