#!/bin/bash

trap '' SIGHUP

source "$botConfig/etc/config"

# consume the input to the command so that the pipe does not fill
grep --line-buffered "^" <&0 > /dev/null &

updateUptime() {
  local -ri started="$(stat -c %Z "$bufferDir")"
  if (($?)); then
    local -ri current="$(date +%s)"

    local -ri elapsed=$((current - started))
    local -i previous
    previous=$(cat "$botLogs/uptime")
    if (($?)) || ((previous < elapsed)); then
      echo "$elapsed" > "$botLogs/uptime"
    fi
  fi
}

thirtyLoop() {
  while true; do
    if (( $(date +%s) - $(cat "$bufferDir/etc/lastContact") > 300 )); then
      echo "Restarted at: $(date +%s) after no contact since $(cat "$bufferDir/etc/lastContact")" >&2
      kill -USR1 $thisPid
    fi

    echo PING "$TARGETSERVER"

    updateUptime

    sleep 30
  done
}

oneTwentyLoop() {
  while true; do
    echo WHOIS $(cat "$bufferDir/etc/nickname") &
    sleep 120
  done
}

oneHourLoop() {
  while true; do
    find "$bufferDir/cache/pastebin/" -name "md5.*" -mtime +6 -exec rm {} \;
    sleep $(( 60 * 60 ))
  done
}

thirtyLoop &
oneTwentyLoop &
oneHourLoop &

wait
