#!/bin/bash

set -f

source "$botLib/irc.sh"
source "$botLib/functionUtils.sh"

watchJoins() {
  local botName="$(< "$bufferDir/etc/nickname")" 
  local channel

  grep --line-buffered -iE "^:$botName!\S+\s+JOIN\s+" \
    | while read -r line; do
        channel="$(getFields "$line" 2)"
        if [[ ! -f "$bufferDir/etc/channels" ]] \
          || ! grep -Fqx "$channel" "$bufferDir/etc/channels"; then
          echo "$channel" >> "$bufferDir/etc/channels" 
        fi
        echo WHO "$channel" %nuhacf &
        privmsg chanserv "op $channel" &
      done
}

startAndWatch watchJoins
