#!/bin/bash

source "$botLib/utility.sh"

watchJoins() {
  local botName="$(< "$bufferDir/etc/nickname")" 
  grep --line-buffered -iE "^:$botName!\S+\s+JOIN\s+" \
    | while read -r line; do
        local channel="$(getFields "$line" 2)"
        if [[ ! -f "$bufferDir/etc/channels" ]] \
          || ! grep -Fqx "$channel" "$bufferDir/etc/channels"; then
          echo "$channel" >> "$bufferDir/etc/channels" 
        fi
        echo WHO "$channel" %nuhacf &
      done
}

startAndWatch watchJoins
