#!/bin/bash

source "$botLib/readprop.sh"
readProperties "$botConfig/etc/config"
declare password
if [[ -f "$botConfig/etc/password" ]]; then
  password="$(< "$botConfig/etc/password")"
fi
export password
trap '' SIGHUP

gawk '

/^:?\S+ NOTICE \* :\*\*\* Looking up your hostname\.\.\./{

  print "NICK " nick
  printf("USER %s %s %s :%s\n", user, hostname, servername, realname)
}

/^:?NickServ!NickServ@services\.\s+NOTICE\s+\S+\s+:This nickname is registered./{
  if (ENVIRON["password"] != "") {
    if (account != "") {
      print "NS identify " account " " ENVIRON["password"]
    } else {
      print "NS identify " ENVIRON["password"]
    }
  }
}' user="${properties[user]}" nick="${properties[nick]}" realname="${properties[realname]}" hostname="${properties[hostname]}" servername="${properties[server]}" account="${properties[account]}"
