#!/bin/bash

source "$botConfig/etc/config"
declare password
if [[ -f "$botConfig/etc/password" ]]; then
  password="$(< "$botConfig/etc/password")"
fi
export password
trap '' SIGHUP

gawk '

/^:?\S+ NOTICE \* :\*\*\* Looking up your hostname\.\.\./{

  print "NICK " nick
  printf("USER %s %s %s :%s\n", user, hostname, servername, realname)
}

/^:?NickServ!NickServ@services\.\s+NOTICE\s+\S+\s+:This nickname is registered./{
  if(ENVIRON["password"] != "") {
    print "NS identify " ENVIRON["password"]
  }
}' user=$USER nick=$NICK realname="$REALNAME" hostname=$HOSTNAME servername=$SERVERNAME
