#!/bin/bash

source "$botLib/utility.sh"

unKarma() {
  local botName="$(< "$bufferDir/etc/nickname")" 
  local -a reactions

  grep --line-buffered -iE "^\S+\s+privmsg\s+#\S+\s+:(($botName[:,] --(\b|$))|(.*\b$botName--(\b|$)))" \
    | while read -r line; do
      read -r sender channel cmd username hostname <<<"$(getIRCInfo "$line")"

      getMessage decrementreply "$sender" | privmsg "$channel" 
      
    done
  
}

# Wrapper for all watchers
#
# completely unnecessary at this point but I don't want to forget
observe() {
  unKarma
} 

startAndWatch observe

