#!/bin/bash

set -f

source "$botLib/functionUtils.sh"
source "$botLib/irc.sh"

parseCommands() {
  local botName="$(< "$bufferDir/etc/nickname")" 

  local -a data
  local message
  local command
  local commandName
  local justMessage

  grep --line-buffered -iE "^\S+\s+privmsg\s+((#\S+\s+:(($botName\>)|(\./)))|([^#[:space:]]+\s+:))" \
    | while read -r line; do
      data=( $(getIRCInfo "$line") ) 
      message="$(getMessageNoNick "$line" "$botName")"

      command="${message%%[[:space:]]*}"
      commandName="${command##./}"
      if [[ ! $commandName =~ [^a-zA-Z0-9] ]]; then
        justMessage="$(sed -E 's/^\s+//' <<< "${message##$command}")"
        if [[ -e "$botLib/commands/simple/$commandName" ]]; then
          # run command with the following params
          # FROMNICK FROMNICK/CHANNEL CMD USERNAME HOSTNAME MESSAGE
          "$botLib/commands/simple/$commandName" "${data[@]}" "$justMessage" "$message" &
        fi
      fi
    done
}

startAndWatch parseCommands
