#!/bin/bash

source "$botLib/utility.sh"

parseCommands() {
  local botName="$(cat "$bufferDir/etc/nickname")" 
  grep --line-buffered -iE "^\S+\s+privmsg\s+((#\S+\s+:(($botName\>)|(\./)))|([^#[:space:]]+\s+:))" \
    | while read -r line; do
      local -a data=( $(getIRCInfo "$line") ) 
      local message="$(getMessageNoNick "$line" "$botName" )"

      local command="${message%%[[:space:]]*}"
      command="${command##./}"
      if [[ ! $command =~ [^a-zA-Z0-9] ]]; then
        if [ -e "$botLib/commands/simple/$command" ]; then
          # run command with the following params
          # FROMNICK FROMNICK/CHANNEL CMD USERNAME HOSTNAME MESSAGE
          "$botLib/commands/simple/$command" "${data[@]}" "$message" &
        fi
      fi
    done
}

startAndWatch parseCommands
