#!/bin/bash

source "$botLib/utility.sh"

set -f

declare -r subRegex='^\S+\s+privmsg\s+#\S+\s+:([^:[:space:]+]*)(\+[1-9][0-9]*)?:s.*$'

substitute() {
  local -ri maxLength="$((510 - $(getheaderlength) - 50))"
  grep --line-buffered -iE "$subRegex" \
    | while read -r line; do
      expression="$(cut -d : -f 3- <<< "$line" | regex.awk)"
      if [[ -n "$expression" ]]; then

        read -r nick channel cmd username hostname <<<"$(getIRCInfo "$line")"
        read -r targetUser targetLine \
          <<<"$(sed -E "s/$subRegex/\\1 \\2/i" <<< "$line")"

        sub "$nick" "$botLogs/$channel" "$expression" "$targetUser" "$targetLine" \
          | sed -E 's/^/=> /' \
          | cut -c-"$maxLength" \
          | tr -d "\a\r\v\n" \
          | privmsg "$channel"
      fi
    done
}

startAndWatch substitute
